AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
