# frozen_string_literal: true

module Strands
  module Types
    # Event loop-related type definitions for the SDK.
    module EventLoop
      # Token usage information for model interactions.
      #
      # @attr input_tokens [Integer] tokens sent in the request
      # @attr output_tokens [Integer] tokens generated by the model
      # @attr total_tokens [Integer] total tokens (input + output)
      # @attr cache_read_input_tokens [Integer, nil] tokens read from cache
      # @attr cache_write_input_tokens [Integer, nil] tokens written to cache
      Usage = Struct.new(
        :input_tokens,
        :output_tokens,
        :total_tokens,
        :cache_read_input_tokens,
        :cache_write_input_tokens,
        keyword_init: true
      ) do
        def initialize(input_tokens:, output_tokens:, total_tokens: nil, cache_read_input_tokens: nil, cache_write_input_tokens: nil)
          super(
            input_tokens: input_tokens,
            output_tokens: output_tokens,
            total_tokens: total_tokens || (input_tokens + output_tokens),
            cache_read_input_tokens: cache_read_input_tokens,
            cache_write_input_tokens: cache_write_input_tokens
          )
        end
      end

      # Performance metrics for model interactions.
      #
      # @attr latency_ms [Integer] latency in milliseconds
      # @attr time_to_first_byte_ms [Integer, nil] time to first content chunk in milliseconds
      Metrics = Struct.new(:latency_ms, :time_to_first_byte_ms, keyword_init: true)

      # Valid stop reasons for model response generation.
      STOP_REASONS = %i[
        cancelled
        checkpoint
        content_filtered
        end_turn
        guardrail_intervened
        interrupt
        limit_output_tokens
        limit_total_tokens
        limit_turns
        max_tokens
        stop_sequence
        tool_use
      ].freeze
    end
  end
end
